# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-20 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locator',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('scu_id', models.CharField(max_length=100)),
            ],
        ),
    ]
