# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-20 11:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locator',
            options={'ordering': ['-created']},
        ),
    ]
